SqlLab/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.debug import default_urlconf

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^SqlLabApp/', include('SqlLabApp.urls')),
    url(r'^$', default_urlconf),
]

SqlLabApp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import TemplateView
from SqlLabApp.views.login import LoginFormView, MainView, RegistrationFormView
from SqlLabApp.views.module import InstructorModuleFormView
from SqlLabApp.views.uploadstudents import TeacherManageModuleFormView
from SqlLabApp.views.test import InstructorTestFormView
from SqlLabApp.views.createmodule import CreateModuleFormView
from SqlLabApp.views.createtest import CreateTestFormView
from SqlLabApp.views.taketest import TakeTestFormView
from SqlLabApp.views.editmodule import EditModuleFormView
from SqlLabApp.views.deletemodule import DeleteModuleView
from SqlLabApp.views.edittest import EditTestFormView
from SqlLabApp.views.reviewtest import ReviewTestFormView
from SqlLabApp.views.studentattemptlist import StudentListFormView
from SqlLabApp.views.deletetest import DeleteTestView
from SqlLabApp.views.testattempt import TestAttemptFormView
from SqlLabApp.views.helpguide import HelpView
from SqlLabApp.views.documentation import DocumentationView
from SqlLabApp.jquerymethods import execute_query

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', MainView.as_view(), name='main'),
    url(r'^login/$', LoginFormView.as_view(), name='login'),
    url(r'^register/$', RegistrationFormView.as_view(), name='register'),
    url(r'^module/$', InstructorModuleFormView.as_view(), name='module'),
    url(r'^createmodule/$', CreateModuleFormView.as_view(), name='createmodule'),
    url(r'^(?P<class_id>[\w\-]+)/test/$', InstructorTestFormView.as_view(), name='test'),
    url(r'^(?P<class_id>[\w\-]+)/createtest/$', CreateTestFormView.as_view(), name='createtest'),
    url(r'^(?P<test_id>[\w\-]+)/taketest/$', TakeTestFormView.as_view(), name='taketest'),
    url(r'^(?P<class_id>[\w\-]+)/editmodule/$', EditModuleFormView.as_view(), name='editmodule'),
    url(r'^(?P<class_id>[\w\-]+)/deletemodule/$', DeleteModuleView.as_view(), name='deletemodule'),
    url(r'^(?P<test_id>[\w\-]+)/studentlist/$', StudentListFormView.as_view(), name='studentlist'),
    url(r'^(?P<tables>.*)/reviewtest/$', ReviewTestFormView.as_view(), name='reviewtest'),
    url(r'^(?P<test_id>[\w\-]+)/edittest/$', EditTestFormView.as_view(), name='edittest'),
    url(r'^(?P<test_id>[\w\-]+)/deletetest/$', DeleteTestView.as_view(), name='deletetest'),
    url(r'^(?P<test_id>[\w\-]+)/testattempt/$', TestAttemptFormView.as_view(), name='testattempt'),
    url(r'^(?P<class_id>[\w\-]+)/teachermanagemodule/$', TeacherManageModuleFormView.as_view(), name='teachermanagemodule'),
    url(r'^help/$', HelpView.as_view(), name='help'),
    url(r'^documentation/$', DocumentationView.as_view(), name='documentation'),
    url(r'^(?P<test_id>[\w\-]+)/taketest/execute_query/', execute_query, name='executequery'),
]

SqlLabApp/models.py
from __future__ import unicode_literals

from datetime import datetime
from django.contrib.auth.base_user import AbstractBaseUser
from django.db import models


class User(AbstractBaseUser):
    email = models.EmailField(max_length=100, primary_key=True)
    password = models.CharField(max_length=100, null=False)
    full_name = models.CharField(max_length=100, default="", null=False)
    USERNAME_FIELD = 'email'

    def get_full_name(self):
        return self.full_name

    def set_full_name(self, fname):
        self.full_name = fname

    def get_short_name(self):
        pass

    def get_full_name(self):
        pass


class UserRole(models.Model):
    class Meta:
        unique_together = (('email', 'role'),)

    email = models.ForeignKey(User)
    role = models.CharField(max_length=3)


class Class(models.Model):
    classid = models.AutoField(primary_key=True)
    class_name = models.CharField(max_length=100, null=False)
    semester = models.CharField(max_length=100, null=True)
    facilitators = models.CharField(max_length=100, null=True)


class ClassTeacherTeaches(models.Model):
    class Meta:
        unique_together = (('classid', 'teacher_email'),)

    classid = models.ForeignKey(Class)
    teacher_email = models.ForeignKey(User)


class ClassStudentAttends(models.Model):
    class Meta:
        unique_together = (('classid', 'student_email'),)

    classid = models.ForeignKey(Class)
    student_email = models.EmailField(max_length=100) # cannot be foreign key as the students
                                                      # might not have signed up when teacher uploads


class TestForClass(models.Model):
    tid = models.AutoField(primary_key=True)
    classid = models.ForeignKey(Class)
    start_time = models.DateTimeField(default=datetime.now, blank=True)
    end_time = models.DateTimeField(default=datetime.now, blank=True)
    test_name = models.CharField(max_length=100, null=False)
    # dyanmic Sql Table is created "tid1.test_name" to store all Questions
    max_attempt = models.IntegerField(null=True, default=None)  # if null, assume unlimited


class StudentAttemptsTest(models.Model):
    class Meta:
        unique_together = (('tid', 'student_email', 'attempt_no'),)

    tid = models.ForeignKey(TestForClass)
    student_email = models.ForeignKey(User)
    attempt_no = models.IntegerField()
    date_submitted = models.DateTimeField(default=datetime.now, blank=True, null=False)
    # dynamic Sql Table = format(tid, student_email, attempt_no)


class QuestionDataUsedByTest(models.Model):
    class Meta:
        unique_together = (('tid', 'data_tbl_name'),)

    tid = models.ForeignKey(TestForClass)
    data_tbl_name = models.CharField(max_length=100, null=False)
    student_visibility = models.BooleanField(default=True)
    # dyanamic Sql Table is created "tid1.Employee1" to store Data tables which will be queried against.


class QuestionAnswer(models.Model):
    qid = models.IntegerField(primary_key=True)
    question = models.CharField(max_length=100, null=False)
    answer = models.CharField(max_length=100, null=False)
    mark = models.IntegerField()

SqlLabApp/forms/createmodule.py
from django import forms


class CreateModuleForm(forms.Form):
    class_name = forms.CharField(widget=forms.widgets.TextInput(attrs={}), label='Module Name')
    semester = forms.CharField(widget=forms.widgets.TextInput(attrs={}), label='Semester')
    facilitators = forms.CharField(widget=forms.widgets.TextInput(attrs={}), label='Facilitators')

    class Meta:
        fields = ['class_name', 'semester', 'facilitators']

SqlLabApp/forms/createtest.py
import datetime
import time
from django import forms


class CreateTestForm(forms.Form):
    test_name = forms.CharField(widget=forms.widgets.TextInput(attrs={}), label='Test Name')
    start_time = forms.CharField(widget=forms.widgets.DateTimeInput(attrs={}), label='Start Date')
    end_time = forms.CharField(widget=forms.widgets.DateTimeInput(attrs={}), label='End Date')
    max_attempt = forms.IntegerField(widget=forms.widgets.NumberInput(
                    attrs={'min': '0'}),
                    label='Number of Attempts', initial=None, required=False)
    q_a_file_upload = forms.FileField(label="Upload Tab Separated File (.txt, .tsv)")
    data_file_upload = forms.FileField(label="Upload .sql dump")

    class Meta:
        fields = ['test_name','start_time', 'end_time', 'max_attempt', 'q_a_file_upload', 'data_file_upload']

    def clean(self):
        start_time = self.data.get('start_time')
        end_time = self.data.get('end_time')
        current_time = datetime.datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d %H:%M:%S')

        if end_time <= current_time:
            raise forms.ValidationError("End date cannot be in the past.")

        if start_time >= end_time:
            raise forms.ValidationError("Start date should be before end date.")

        return start_time

SqlLabApp/forms/editmodule.py
from django.forms import ModelForm
from SqlLabApp.models import Class


class EditModuleForm(ModelForm):
    class Meta:
        model = Class
        fields = ['class_name', 'semester', 'facilitators']

SqlLabApp/forms/edittest.py
import datetime
import time
from django import forms
from django.forms import ModelForm
from SqlLabApp.models import TestForClass


class EditTestForm(ModelForm, forms.Form):
    class Meta:
        model = TestForClass
        fields = ['start_time', 'end_time', 'max_attempt']

    def __init__(self, dynamic_field_names, *args, **kwargs):
        super(EditTestForm, self).__init__(*args, **kwargs)

        for row in dynamic_field_names:
            field_name = row['name']
            visi = row['visibility']
            self.fields[field_name] = forms.BooleanField(label=field_name.title(), required=False, label_suffix='', initial=visi)

SqlLabApp/forms/instructor.py
from django import forms


class InstructorForm(forms.Form):

     class Meta:
        fields = [ ]

SqlLabApp/forms/instructormodule.py
from django import forms


class InstructorModuleForm(forms.Form):

    class Meta:
        fields = []

SqlLabApp/forms/instructortest.py
from django import forms


class InstructorTestForm(forms.Form):

     class Meta:
        fields = []

SqlLabApp/forms/login.py
from django import forms


class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.widgets.TextInput(attrs={'placeholder': 'Email'}), label='')
    password = forms.CharField(widget=forms.widgets.PasswordInput(attrs={'placeholder': 'Password'}), label='')

    class Meta:
        fields = ['email', 'password']

SqlLabApp/forms/module.py
from django import forms


class InstructorModuleForm(forms.Form):

    class Meta:
        fields = []

SqlLabApp/forms/register.py
from django import forms
from SqlLabApp.models import User, UserRole


class RegistrationForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Email'}), label='')
    full_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Full Name'}), label='')
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}), label='')
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}), label='')
    INSTRUCTOR = "INS"
    STUDENT = "STU"
    roles_choices = [(INSTRUCTOR, "Instructor"), (STUDENT, "Student")]
    role = forms.ChoiceField(choices=roles_choices, label='')

    class Meta:
        model = User
        fields = ['email', 'full_name', 'password1', 'password2']

    def clean(self):
        """
        Verifies that the values entered into the password fields match

        NOTE: Errors here will appear in ``non_field_errors()`` because it applies to more than one field.
        """
        cleaned_data = super(RegistrationForm, self).clean()
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError("Passwords don't match. Please enter both fields again.")
        return self.cleaned_data

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user_role = UserRole(email_id=self.cleaned_data['email'], role=self.cleaned_data['role'])
        if commit:
            user.save()
            user_role.save()
        return user

SqlLabApp/forms/reviewtest.py
from django import forms


class ReviewTestForm(forms.Form):

    class Meta:
        fields = []

SqlLabApp/forms/studentattemptlist.py
from django import forms


class StudentListForm(forms.Form):

     class Meta:
        fields = []

SqlLabApp/forms/studentlist.py
from django import forms


class StudentListForm(forms.Form):

     class Meta:
        fields = []

SqlLabApp/forms/taketest.py
from django import forms


class TakeTestForm(forms.Form):
    
    student_answer = forms.CharField(widget=forms.Textarea, label='', required=True)

SqlLabApp/forms/teacher_manage_module.py
from django.forms import forms


class TeacherManageModule(forms.Form):
    student_list_file_upload = forms.FileField(label="Upload List of Students .txt")

    class Meta:
        fields = ["student_list_file_upload"]

SqlLabApp/forms/test.py
from django import forms


class InstructorTestForm(forms.Form):

     class Meta:
        fields = []

SqlLabApp/forms/testattempt.py
from django import forms


class TestAttemptForm(forms.Form):

     class Meta:
        fields = []

SqlLabApp/forms/uploadstudentlist.py
from django.forms import forms


class TeacherManageModule(forms.Form):
    student_list_file_upload = forms.FileField(label="Upload List of Students .txt")

    class Meta:
        fields = ["student_list_file_upload"]

SqlLabApp/views/createmodule.py
import os

from django.db import transaction
from django.http import HttpResponseRedirect
from django.views.generic import FormView

from SqlLabApp.forms.createmodule import CreateModuleForm
from SqlLabApp.models import User, Class, ClassTeacherTeaches
from SqlLabApp.utils.DBUtils import get_db_connection


class CreateModuleFormView(FormView):
    form_class = CreateModuleForm
    template_name = 'SqlLabApp/createmodule.html'
    success_url = '/'

    def get(self, request, *args, **kwargs):
        full_name = User.objects.get(email=request.user.email).full_name

        return self.render_to_response(
            self.get_context_data(
                full_name=full_name
            )
        )

    def post(self, request, *args, **kwargs):
        create_module_form = self.form_class(request.POST, request.FILES)

        if create_module_form.is_valid():
            class_name = request.POST['class_name']
            semester = request.POST['semester']
            facilitators = request.POST['facilitators']
            # student_list_file = request.POST['student_list_file']
            #
            # if student_list_file is None:
            #     raise ValueError("No Upload for student file")
            #
            # student_list_file_lines = student_list_file.read().splitlines()

            try:
                with transaction.atomic():
                    class_ = Class(class_name=class_name, semester=semester, facilitators=facilitators)
                    class_.save()

                    class_teacher_teaches = ClassTeacherTeaches(teacher_email_id=request.user.email, classid=class_)
                    class_teacher_teaches.save()

            except ValueError as err:
                raise err

            return HttpResponseRedirect("../module")

        else:
            raise ValueError(create_module_form.errors)


def validate_student_list_file(filename, q_a_file_lines):
    file_ext = os.path.splitext(filename)[1]
    valid_extensions = ['.tsv', '.txt']

    if file_ext.lower() not in valid_extensions:
        raise ValueError("Only tsv or txt files are allowed")

    for row in q_a_file_lines:
        splitted = row.split("\t")
        if len(splitted) != 2:
            raise ValueError("Expected Student Email <tab> Student Name".format(row))

SqlLabApp/templates/SqlLabApp/createtest.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="SqlLab">
    <meta name="author" content="SqlLab">

    <title>SqlLab</title>

    {% load staticfiles %}

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>

    <!-- jQuery -->
    <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">
    <link rel="stylesheet" href="{% static 'css/createtest.css' %}">

    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href='//fonts.googleapis.com/css?family=Dekko' rel='stylesheet'>
    <link href='//fonts.googleapis.com/css?family=Assistant' rel='stylesheet'>
    <link href='//fonts.googleapis.com/css?family=Gloria Hallelujah' rel='stylesheet'>
    <link href='//fonts.googleapis.com/css?family=Open Sans' rel='stylesheet'>

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body id="page-top" class="index">
{% block content %}

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a href="{% url 'module' %}">
                    <h1>SqLLAB</h1>
                </a>
            </div>
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <div class="dropdown">
                            <a href="{% url 'module' %}">My Modules</a>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <a href="{% url 'documentation' %}" target="_blank">Documentation</a>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <a href="{% url 'help' %}" target="_blank">Help</a>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <a>{{ full_name }}&ensp;&ensp;▾</a>
                            <div class="dropdown-content">
                                <a href="{% url 'main' %}">Logout</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <form class="form" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <script type="text/javascript">
                        $("#id_start_time").datetimepicker({
                            format: 'YYYY-MM-DD HH:mm'
                        });
                        $("#id_end_time").datetimepicker({
                            format: 'YYYY-MM-DD HH:mm'
                        });
                    </script>
                    <button id="create-test" class="btn" type="submit">CREATE NEW TEST</button>
                </form>
            </div>
        </div>
    </header>

{% endblock %}
</body>

SqlLabApp/templates/SqlLabApp/edittest.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="SqlLab">
    <meta name="author" content="SqlLab">

    <title>SqlLab</title>

    {% load staticfiles %}

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>

    <!-- jQuery -->
    <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">
    <link rel="stylesheet" href="{% static 'css/createtest.css' %}">

    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href='//fonts.googleapis.com/css?family=Dekko' rel='stylesheet'>
    <link href='//fonts.googleapis.com/css?family=Assistant' rel='stylesheet'>
    <link href='//fonts.googleapis.com/css?family=Gloria Hallelujah' rel='stylesheet'>
    <link href='//fonts.googleapis.com/css?family=Open Sans' rel='stylesheet'>

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body id="page-top" class="index">
{% block content %}

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a href="{% url 'module' %}">
                    <h1>SqLLAB</h1>
                </a>
            </div>
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <div class="dropdown">
                            <a href="{% url 'module' %}">My Modules</a>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <a href="{% url 'documentation' %}" target="_blank">Documentation</a>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <a href="{% url 'help' %}" target="_blank">Help</a>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <a>{{ full_name }}&ensp;&ensp;▾</a>
                            <div class="dropdown-content">
                                <a href="{% url 'main' %}">Logout</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <form class="form" action={% url 'edittest' test.tid %} method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button id="create-test" class="btn" type="submit">EDIT TEST</button>
                </form>
                <script type="text/javascript">
                    $("#id_start_time").datetimepicker({format: 'YYYY-MM-DD HH:mm'});
                    $("#id_end_time").datetimepicker({format: 'YYYY-MM-DD HH:mm'});
                </script>
            </div>
        </div>
    </header>

{% endblock %}
</body>

SqlLabApp/templates/SqlLabApp/reviewtest.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="SqlLab">
    <meta name="author" content="SqlLab">

    <title>SqlLab</title>

    {% load staticfiles %}

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

    <!-- jQuery -->
    <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">
    <link rel="stylesheet" href="{% static 'css/reviewtest.css' %}">
    <link rel="stylesheet" href="{% static 'css/popup.css' %}">

    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href='//fonts.googleapis.com/css?family=Dekko' rel='stylesheet'>
    <link href='//fonts.googleapis.com/css?family=Assistant' rel='stylesheet'>
    <link href='//fonts.googleapis.com/css?family=Gloria Hallelujah' rel='stylesheet'>
    <link href='//fonts.googleapis.com/css?family=Open Sans' rel='stylesheet'>

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body id="page-top" class="index">
{% block content %}

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a href="{% url 'module' %}">
                    <h1>SqLLAB</h1>
                </a>
            </div>
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <div class="dropdown">
                            <a href="{% url 'module' %}">My Modules</a>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <a href="{% url 'documentation' %}" target="_blank">Documentation</a>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <a href="{% url 'help' %}" target="_blank">Help</a>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <a>{{ full_name }}&ensp;&ensp;▾</a>
                            <div class="dropdown-content">
                                <a href="{% url 'main' %}">Logout</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div id="module-header">
                    <h2>{{ test_name }}</h2>
                </div>
                {% for question, answer, marks, correctness in test_data %}
                    <div id="action-container">
                        <div class="row">
                            <div class="col-md-9">
                                <h4>{{ question }}</h4>
                            </div>
                            <div class="col-md-3">
                                {% if correctness %}
                                    <h4 style="text-align: right; color: #1e9f75; font-size: 16px">Marks Obtained: {{ marks }}</h4>
                                {% else %}
                                    <h4 style="text-align: right; color: #f00009; font-size: 16px">Marks Obtained: {{ marks }}</h4>
                                {% endif %}
                            </div>
                            <br>
                        </div>
                        <textarea cols="40" id="id_student_answer" name="student_answer" rows="10" disabled>Your Answer: {{ answer }}</textarea>
                    </div>
                {% endfor %}
            </div>
        </div>
    </header>

{% endblock %}
</body>